### ISSUE TITLE
question

### ISSUE THREAD

**Issue by bondz** [micromatch/braces#15]
Snyk says this vulnerability has been fixed, but still lists the current version of the package as vulnerable. Has it?

https://snyk.io/vuln/npm:braces:20180219

This affects a lot of dependents.

**Comment by jonschlinkert** [comment]
1) It was fixed immediately after it was reported
2) it wasn't "a potential vulnerability". this was discussed at length elsewhere. 
3) you should never create an issue like this about a potential vulnerability unless you want to either incite panic or actually cause the problem that everyone wants to avoid.
