### ISSUE TITLE
Regular Expression Denial of Service vulnerability detected

### ISSUE THREAD

**Issue by cgds188** [micromatch/braces#20]
Below vulnerability is detected via npm version 6.4.1
Regular Expression Denial of Service (as low severity)

Manual Review
Some vulnerabilities require your attention to resolve
Visit https://go.npm.me/audit-guide for additional guidance

  Low             Regular Expression Denial of Service

  Package         braces

  Patched in      >=2.3.1

**Comment by jonschlinkert** [comment]
This was fixed a long time ago.
