### ISSUE TITLE
documentation: "keepEscaping" is missing

### ISSUE THREAD

**Issue by vemoo** [micromatch/braces#26]
I'm not sure if it's a braces or micromatch issue, but 
```js
braces("C:/Program Files \\(x86\\)")
```
returns 
```js
[ "C:/Program Files (x86)" ]
```
losing the escape characters, making 
```js
micromatch.parse("C:/Program Files \\(x86\\)")
```
return the tokens
```js
[
	{
		"type": "bos",
		"value": "",
		"output": ""
	},
	{
		"type": "text",
		"value": "C:"
	},
	{
		"type": "slash",
		"value": "/",
		"output": "\\/"
	},
	{
		"type": "text",
		"value": "Program Files "
	},
	{
		"type": "paren",
		"value": "("
	},
	{
		"type": "text",
		"value": "x86"
	},
	{
		"type": "paren",
		"value": ")",
		"output": ")"
	}
]
```
vs what I expected and what
```js
picomatch.parse("C:/Program Files \\(x86\\)")
```
returns
```js
[
	{
		"type": "bos",
		"value": "",
		"output": ""
	},
	{
		"type": "text",
		"value": "C:"
	},
	{
		"type": "slash",
		"value": "/",
		"output": "\\/"
	},
	{
		"type": "text",
		"value": "Program Files \\(x86\\)"
	}
]
```

Here's some sample code: https://repl.it/repls/SharpStrangeChemistry

**Comment by vemoo** [comment]
I've realized theres options.unescape but it doesn't seem to do anything in this case.

**Comment by jonschlinkert** [comment]
That's not right, this is a bug, and it's inconsistent with how picomatch works. It should allow you to retain escaping. Thank you for reporting it.

**Comment by jonschlinkert** [comment]
ah, wait. The option is `keepEscaping`. I forgot that I used a different option name to allow you to escape one or the other, or both. If both picomatch and braces had the same option name (`unescape`) for this specifically, you wouldn't be able to control escaping. 

Try this:

```js
console.log(braces("C:/Program Files \\(x86\\)", { keepEscaping: true }));
```

**Comment by vemoo** [comment]
Yes, that works. Then the documentation should be updated and it should be added to the documentation of micromatch.

**Comment by jonschlinkert** [comment]
> Then the documentation should be updated and it should be added to the documentation of micromatch.

Agreed! Thanks for reporting this. Want to do a PR?
