### ISSUE TITLE
Braces with a single value are not expanded

### ISSUE THREAD

**Issue by iiroj** [micromatch/braces#32]
Hello,

I'm not sure if this is a feature or not, but braces containing only a single value do not get expanded properly.

Two values work fine:

```bash
❯ node -e "console.log(require('braces')('{x,y}', { expand:true }))"
[ 'x', 'y' ]
```

However, only a single value doesn't:

```bash
❯ node -e "console.log(require('braces')('{x}', { expand:true }))" 
[ '{x}' ]
```

I would expect it to instead return:

```bash
❯ node -e "console.log(require('braces')('{x}', { expand:true }))" 
[ 'x' ]
```

**Comment by jonschlinkert** [comment]
This is correct behavior, per bash. This is documented on the readme: https://github.com/micromatch/braces/blob/98414f9f1fabe021736e26836d8306d5de747e0d/README.md#escaping

**Comment by jonschlinkert** [comment]
Closing since I think this is resolved. Please feel free to reopen if you think this needs to be discussed further.

**Comment by iiroj** [comment]
Thanks! It makes sense. It's just a common misconfiguration issue with [lint-staged](https://github.com/okonet/lint-staged), where users write globs like `*.{jsx,tsx}` and then also `*.{json}`. I think we just need to add something about it to the README. These are used for `micromatch`.

**Comment by jonschlinkert** [comment]
Totally understand! I’ve done it as well!
